article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('contact/',views.contact,name = "contact"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author ")
    title = models.CharField(max_length = 50,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Date Created")
    article_image = models.FileField(blank = True,null = True,verbose_name="Add Photo to Article")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "User name")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "User name")
    password = forms.CharField(max_length=20,label = "Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Verify Password",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Do Not Match")

        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    articles = Article.objects.all()
    return render(request,"index.html",{"articles":articles})
    
def about(request):
    return render(request,"about.html")

def contact(request):
    return render(request,"contact.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article created successfully")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article = Article.objects.filter(id = id).first()   
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article updated successfully")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Article Deleted Successfully")

    return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout



# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"You have successfully registered ...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

    
    
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Username or Password Incorrect")
            return render(request,"login.html",context)

        messages.success(request,"You have successfully logged in")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
def logoutUser(request):
    logout(request)
    messages.success(request,"Successfully logged out")
    return redirect("index")

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Article</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3></h3>
<div class="w3-head-all  py-md-3">
            <h3 class="text-uppercase mt-4">Dashboard of {{request.user.username}}</h3>
              
      </div>
      <div class="container jumbotron">
      <h4>Welcome to your Dashboard. Here you can Manage your Articles by adding a new artcle or by editing an old one.</h4><br>
<a class = "btn btn-success" href = "{% url 'article:addarticle' %}">Add Article</a>
</div>
{% if articles %}
<div class="container jumbotron">
<table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Date</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-warning">Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
      </div>
{% else %}

<div class = "alert alert-danger">
  You have no articles yet ...

</div>
{% endif %}



{% endblock body %}

templates/includes/footer.html
<!-- footer -->
<section class="agile-footer w3ls-section py-5">
    <div class="container">
      <div class="list-footer">
        <ul class="footer-nav text-center">
          <li>
            <a href="{% url 'index'  %}">Home</a>
          </li>
          <li>
            <a href="{% url 'about'  %}">About</a>
          </li>
          <li>
            <a href="{% url 'article:articles' %}">Articles</a>
          </li>
          {% if request.user.is_authenticated %}
            <li>
              <a href="{% url 'article:dashboard'  %}">Dashboard</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'user:register'  %}">Register</a>
            </li>
          {% endif %}
          <li>
            <a href="{% url 'contact' %}">Contact</a>
          </li>
        </ul>
      </div>
      <div class="agileits_w3layouts-footer-bottom">
        <div class="row w3_agile-footer-grids py-5 my-4">
          <div class="col-lg-3 col-sm-12 w3_agile-footer1 f1">
            <h2 class="mb-3">
              <a href="{% url 'index'  %}">Blog App</a>
            </h2>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem atus error sit volupt unde.</p>
          </div>
          <div class="col-lg-7 col-sm-12 row w3_agile-footer1 f2">
            <div class="col-lg-4  col-sm-4 inner-li">
              <h5 class="mb-3">Social</h5>
              <ul class="w3ls-footer-bottom-list">
                <li>
                  <a class="page-scroll" href="https://www.facebook.com/akshukla007" title="Friend me on Facebook">
                    <i class="fab fa-facebook-f"></i> Facebook</a>
                </li>
                <li>
                  <a class="page-scroll" href="https://twitter.com/Aag_Shukla" title="Follow me on Twitter">
                    <i class="fab fa-twitter"></i>  Twitter</a>
                </li>
                <li>
                  <a class="page-scroll" href="https://www.instagram.com/aag_shukla" title="Follow me on Instagram">
                    <i class="fab fa-instagram"></i>  Instagram</a>
                </li>
                <li>
                  <a class="page-scroll" href="https://plus.google.com/+AnuragKumarShukla" title="Friend me on Google+">
                    <i class="fab fa-google-plus-g"></i>  Google+</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-4 col-sm-4 inner-li">
              <h5 class="mb-3">Educational</h5>
              <ul class="w3ls-footer-bottom-list">
                <li>
                  <a class="page-scroll" href="https://github.com/AKrShukla" title="Follow me on GitHub">
                    <i class="fab fa-github"></i> GitHub</a>
                </li>
                <li>
                  <a class="page-scroll"  href="https://www.linkedin.com/in/aag-shukla/" title="Connect to me on LinkedIn">
                    <i class="fab fa-linkedin-in"></i> LinkedIn
                  </a>
                </li>
                <li>
                  <a class="page-scroll" href="https://curiousforscience.blogspot.com/" title="Friend me on Facebook">
                    <i class="fab fa-blogger-b"></i>  Blog</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-4 col-sm-4 inner-li">
              <h5 class="mb-3">support</h5>
              <ul class="w3ls-footer-bottom-list">
                <li>
                  <a href="#">24/7 service</a>
                </li>
                <li>
                  <a href="#">FAQ</a>
                </li>
                <!-- <li>
                  <a href="#">media</a>
                </li> -->
              </ul>
            </div>
          </div>
          <div class="col-lg-2 col-sm-4  w3_agile-footer1 f3">
            <h5 class="mb-3">Need Help?</h5>
            <ul class="footer-social-icons">
              <li>
                <a href="{% url 'contact' %}">
                  Contact us
                </a>
              </li>
              <li>
                <a href="mailto:angshkl@gmail.com">
                  Mail Anurag
                </a>
              </li>
              <li>
                <a href="#">
                  +91-70428-55345
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="agileits_w3layouts-copyright text-center">
        <p>© 2018 Anurag Kumar Shukla | All Rights Reserved
        </p>
      </div>
    </div>
  </section>
  <!-- //footer -->

templates/includes/navbar.html
<header>
	<div class="top-nav">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light">
				<a class="navbar-brand text-uppercase" href="{% url 'index'  %}">Blog App<i class="fab fa-python"></i></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse justify-content-center pr-md-4" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							{% if request.path == '/' %}
							<a class="nav-link active" href="{% url 'index'  %}">Home<span class="sr-only">(current)</span></a>
							{% else %}
							<a class="nav-link" href="{% url 'index'  %}">Home<span class="sr-only">(current)</span></a>
							{% endif %}
						</li>
						<li class="nav-item">
							{% if request.path == '/about/' %}
							<a class="nav-link active" href="{% url 'about'  %}">About</a>
							{% else %}
							<a class="nav-link" href="{% url 'about'  %}">About</a>
							{% endif %}
							
						</li>
						<li class="nav-item">
							{% if request.path == '/articles/' %}
							<a class="nav-link active" href="{% url 'article:articles' %}">Articles</a>
							{% else %}
							<a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
							{% endif %}
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
								{% if request.path == '/articles/dashboard/' %}
								<a class="nav-link active" href="{% url 'article:dashboard'  %}">Dashboard</a>
								{% else %}
								<a class="nav-link" href="{% url 'article:dashboard'  %}">Dashboard</a>
								{% endif %}
              </li>
              <li class="nav-item">
								<a class="nav-link" href="{% url 'user:logout'  %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
								{% if request.path == '/user/login/' %}
								<a class="nav-link active" href="{% url 'user:login'  %}">Log in</a>
								{% else %}
								<a class="nav-link" href="{% url 'user:login'  %}">Log in</a>
								{% endif %}
              </li>
              <li class="nav-item">
								{% if request.path == '/user/register/' %}
								<a class="nav-link active" href="{% url 'user:register'  %}">Register</a>
								{% else %}
								<a class="nav-link" href="{% url 'user:register'  %}">Register</a>
								{% endif %}
              </li>
            {% endif %}
					</ul>
				</div>
			</nav>
		</div>
	</div>
</header>
								
								

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Blog App</title>
        <link rel="shortcut icon" type="image/png" href="{{MEDIA_URL}}favicon.png">
            <!-- Meta tag Keywords -->
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta charset="utf-8">
            <meta name="keywords" content="BLOG APP by ANURAG" />
            <script type="application/x-javascript">
                addEventListener("load", function () {
                    setTimeout(hideURLbar, 0);
                }, false);
                function hideURLbar() {
                    window.scrollTo(0, 1);
                }
            </script>
            <!--// Meta tag Keywords -->
        
            <!-- css files -->
            <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}"> <!-- Bootstrap-Core-CSS -->
            <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS --> 
            <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.css' %}"> <!-- Font-Awesome-Icons-CSS -->
            <!-- //css files -->
            <link href="{% static 'assets/css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>
            <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" /><!-- Calendar -->
            <!-- testimonials css -->
            <link rel="stylesheet" href="{% static 'assets/css/flexslider.css' %}" type="text/css" media="screen" property="" /><!-- flexslider css -->
            <!-- //testimonials css -->
            <style>
            .navbar-custom {
                background-color: #006064;
            }
            body {
                color: #004d40;
            }
            .icon-link {
                text-decoration: none;
                color: inherit;
            }
            p {
                color: #004d40;
            }
            .bcx {
                width : 400px;
                height: 260px;
            }
            .searchbar {
                width: 86%;
                padding: 0.375rem 0.75rem;
                font-size: 1rem;
                line-height: 1.5;
                color: #495057;
                background-color: #fff;
                background-clip: padding-box;
                border: 1px solid #ced4da;
                border-radius: 0.25rem;
                transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
            }</style>
            <!-- web-fonts -->
            <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
            <link href="//fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
            <!-- //web-fonts -->
</head>
    <body >  
        {% include "includes/navbar.html" %}
        {% if request.path == '/' %}
            <!--Slider-->
            <div class="slider">
                <div class="callbacks_container">
                    <ul class="rslides callbacks callbacks1" id="slider4">
                        <li>
                            <div class="slider-img1">
                                <div class="dot">
                                    <div class="container">
                                        <div class="slider_banner_info_w3ls">
                                            <h1 class="text-uppercase mb-3">Welcome to the Blog App</h1>
                                            <p>Etiam vitae augue odio. Ut laoreet ipsum vel ultrices viverra. Donec nisl dolor, mollis vel libero id, 
                                                    tempor cursus lectus. Vestibulum eu ligula et pharetra efficitur. Maecenas eleifend.</p>

                                            <a href="{% url 'user:register'  %}" class="read" role="button">Register Yourself</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="slider-img2">
                                <div class="dot">
                                    <div class="container">
                                        <div class="slider_banner_info_w3ls">
                                            <h4 class="text-uppercase mb-3">Create and Manage Articles</h4>
                                            <p>Etiam vitae augue odio. Ut laoreet ipsum vel ultrices viverra. Donec nisl dolor, mollis vel libero id, 
                                                    tempor cursus lectus. Vestibulum eu ligula et pharetra efficitur. Maecenas eleifend.</p>
                                            {% if request.user.is_authenticated %}
                                                <a href="{% url 'article:dashboard'  %}" class="read" role="button">Go to your Dashboard</a>
                                            {% else %}
                                                <a href="{% url 'user:login'  %}" class="read" role="button">Login</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="slider-img3">
                                <div class="dot">
                                    <div class="container">
                                        <div class="slider_banner_info_w3ls">
                                            <h4 class="text-uppercase mb-3">Read Articles as you Write them</h4>
                                            <p>Etiam vitae augue odio. Ut laoreet ipsum vel ultrices viverra. Donec nisl dolor, mollis vel libero id, 
                                                    tempor cursus lectus. Vestibulum eu ligula et pharetra efficitur. Maecenas eleifend.</p>

                                            <a href="{% url 'article:articles' %}" class="read" role="button">All Articles</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="slider-img4">
                                <div class="dot">
                                    <div class="container">
                                        <div class="slider_banner_info_w3ls">
                                            <h4 class="text-uppercase mb-3">Take a minute to know us</h4>
                                            <p>Etiam vitae augue odio. Ut laoreet ipsum vel ultrices viverra. Donec nisl dolor, mollis vel libero id, 
                                                    tempor cursus lectus. Vestibulum eu ligula et pharetra efficitur. Maecenas eleifend.</p>

                                            <a href="{% url 'about'  %}" class="read" role="button">About Us</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <div class="clearfix"></div>
                    </ul>
            </div>

            <!--//Slider-->
        {% else %}
            <section class="innerpage_banner py-5">
                <div class="dot1">
                </div>
            </section>
        {% endif %}
        {% comment %} {{ request.path }} {% endcomment %}
        <div class = "container">        
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "info" %}
                        <div class="container">
                            <div class="wthree_head_section stats_head">
                                <h3 >{{ message }}</h3>
                            </div>
                        </div>
                    {% else %}
                        <div class="container">
                            <div class="alert alert-{{ message.tags }}">
                                <h3 >{{ message }}</h3>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        {% block body %} 
        {% endblock body %}
    </body>

    {% include "includes/footer.html" %}
    <!-- js-scripts -->		

	<!-- js -->
	<script type="text/javascript" src="{% static 'assets/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/bootstrap.js' %}"></script> <!-- Necessary-JavaScript-File-For-Bootstrap --> 
	<!-- //js -->	
	
	<!-- Banner Responsive slider -->
	<script src="{% static 'assets/js/responsiveslides.min.js' %}"></script>
	<script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager: false,
				nav: true,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
	</script>
	<!-- // Banner Responsive slider -->
	<!-- script for responsive tabs -->						
    <script src="{% static 'assets/js/easy-responsive-tabs.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion           
                width: 'auto', //auto or any width like 600px
                fit: true,   // 100% fit in a container
                closed: 'accordion', // Start closed if in accordion view
                activate: function(event) { // Callback function if tab is switched
                    var $tab = $(this);
                    var $info = $('#tabInfo');
                    var $name = $('span', $info);
                    $name.text($tab.text());
                    $info.show();
                }
            });
            $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
            });
        });
    </script>
    <!--script for responsive tabs -->
    <!-- Calendar -->
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
        <script>
            $(function() {
                $( "#datepicker,#datepicker1,#datepicker2,#datepicker3" ).datepicker();
            });
        </script>
    <!-- //Calendar -->
    <!-- stats -->
	<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.countup.js' %}"></script>
	<script>
		$('.counter').countUp();
	</script>
	<!-- //stats -->
	<!-- flexSlider --><!-- for testimonials -->
	<script defer src="{% static 'assets/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">
		$(window).load(function(){
		  $('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			  $('body').removeClass('loading');
			}
		  });
		});
	</script>
	<!-- //flexSlider --><!-- for testimonials -->

	<!-- start-smoth-scrolling -->
	<script src="{% static 'assets/js/SmoothScroll.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- here stars scroslling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
	<!-- //here ends scrolling icon -->
	<!-- start-smoth-scrolling -->
	
<!-- //js-scripts -->

</html>

templates/register.html
{% extends "layout.html" %}
{% load static %}
{% block body %}

{% load crispy_forms_tags %}

<link rel="stylesheet" href="{% static 'assets/css/login.css' %}" type="text/css" media="all" />
<section class="register-block">
    <div class="container container2" style="width:65%;">
	<div class="row">
        <div class="col-md-8 offset-md-2 register-sec">
		    <h2 class="text-center">Register a new User</h2>
		    <form method="post" class="login-form center">
                {% csrf_token %}
                {{form|crispy}}
                <div class="form-check">
                <button type="submit" class="btn btn-login float-right">Register</button>
                <div class="row"></div>
            </div>
</form></div></div></section>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update</button>
        </form>
    </div>
  </div>


{% endblock body %}